/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.tsx', './index.js', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      fontFamily: {
        sans: ['DMSans'],
      },
      letterSpacing: {
        sleek: '-0.02em',
        snug: '-0.01em',
        label: '0.08em',
        wide: '0.04em',
      },
      colors: {
        palette: {
          limelight: '#D0E836',
          'yellow-green': '#9ACD32',
          sunflower: '#E5BE2B',
          green: '#2D8A47',
          chartreuse: '#9AE638',
        },
        app: {
          bg: '#F5F8F2',
          'bg-dark': '#0E1410',
          surface: '#FFFFFF',
          'surface-dark': '#182018',
          'surface-raised': '#FAFCF7',
          'surface-raised-dark': '#1F2A22',
          ink: '#142818',
          'ink-dark': '#F0F6EC',
          muted: '#4A634F',
          'muted-dark': '#9AAD9E',
          faint: '#7A917F',
          'faint-dark': '#6B806F',
          border: 'rgba(20, 40, 24, 0.10)',
          'border-dark': 'rgba(240, 246, 236, 0.10)',
          fill: 'rgba(45, 138, 71, 0.12)',
          'fill-dark': 'rgba(154, 205, 50, 0.14)',
          primary: '#2D8A47',
          'primary-dark': '#9ACD32',
          secondary: '#9ACD32',
          'secondary-dark': '#9AE638',
          accent: '#9AE638',
          'accent-dark': '#D0E836',
          highlight: '#D0E836',
          'highlight-dark': '#3A4528',
          warm: '#E5BE2B',
          'warm-dark': '#E5BE2B',
          'on-primary': '#FFFFFF',
          'on-primary-dark': '#0E1410',
          'on-highlight': '#142818',
          'on-highlight-dark': '#F0F6EC',
        },
      },
    },
  },
  plugins: [],
};
